[project]
name = "mcp-demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.12.2",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.7",
]
